[Icon Theme]
Name=Galaxy Theme KDE Icons
Comment=Galaxy Theme KDE - Modern celestial and futuristic SVG icon theme by badcast <lmecomposer@gmail.com>
Inherits=breeze-dark,breeze,hicolor
Example=folder
DisplayDepth=32
FollowsColorScheme=true
KDE-Extensions=.svg
Author=badcast
Email=lmecomposer@gmail.com

Directories=scalable/places,scalable/apps,scalable/actions,scalable/categories,scalable/devices,scalable/mimetypes,scalable/status

[scalable/places]
Size=64
Context=Places
MinSize=16
MaxSize=512
Type=Scalable

[scalable/apps]
Size=64
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[scalable/actions]
Size=24
Context=Actions
MinSize=16
MaxSize=512
Type=Scalable

[scalable/categories]
Size=32
Context=Categories
MinSize=16
MaxSize=512
Type=Scalable

[scalable/devices]
Size=64
Context=Devices
MinSize=16
MaxSize=512
Type=Scalable

[scalable/mimetypes]
Size=64
Context=MimeTypes
MinSize=16
MaxSize=512
Type=Scalable

[scalable/status]
Size=24
Context=Status
MinSize=16
MaxSize=512
Type=Scalable
